<?php

declare(strict_types=1);

return [

    /*
    |--------------------------------------------------------------------------
    | Product identifier (PRODID)
    |--------------------------------------------------------------------------
    | Stamped onto calendars created via ICalendar::calendar(). Identifies the
    | software that generated the file.
    */
    'product_id' => '-//'.env('APP_NAME', 'Laravel').'//iCalendar//EN',

    /*
    |--------------------------------------------------------------------------
    | Strict mode
    |--------------------------------------------------------------------------
    | When true, parsing throws on RFC violations and serialization requires
    | mandatory properties. When false (default), both are lenient.
    */
    'strict' => false,

    /*
    |--------------------------------------------------------------------------
    | Include VTIMEZONE definitions
    |--------------------------------------------------------------------------
    | When true, serializing a calendar auto-injects a VTIMEZONE for each IANA
    | time zone its events use, producing self-contained, portable files.
    */
    'include_timezones' => true,

    /*
    |--------------------------------------------------------------------------
    | Default download filename
    |--------------------------------------------------------------------------
    | Used by ICalendar::response() / the `ics` response macro.
    */
    'filename' => 'calendar.ics',

    /*
    |--------------------------------------------------------------------------
    | UID domain
    |--------------------------------------------------------------------------
    | The right-hand side of UIDs generated by the InteractsWithCalendar trait.
    | Defaults to the host of APP_URL when null.
    */
    'uid_domain' => null,

];
