<?php

declare(strict_types=1);
use Erenav\LaravelICalendar\Models\Calendar;
use Erenav\LaravelICalendar\Models\CalendarEvent;
use Erenav\LaravelICalendar\Models\EventAlarm;
use Erenav\LaravelICalendar\Models\EventParticipant;

return [

    /*
    |--------------------------------------------------------------------------
    | Product identifier (PRODID)
    |--------------------------------------------------------------------------
    | Stamped onto calendars created via ICalendar::calendar(). Identifies the
    | software that generated the file.
    */
    'product_id' => '-//'.env('APP_NAME', 'Laravel').'//iCalendar//EN',

    /*
    |--------------------------------------------------------------------------
    | Strict mode
    |--------------------------------------------------------------------------
    | When true, parsing throws on RFC violations and serialization requires
    | mandatory properties. When false (default), both are lenient.
    */
    'strict' => false,

    /*
    |--------------------------------------------------------------------------
    | Include VTIMEZONE definitions
    |--------------------------------------------------------------------------
    | When true, serializing a calendar auto-injects a VTIMEZONE for each IANA
    | time zone its events use, producing self-contained, portable files.
    */
    'include_timezones' => true,

    /*
    |--------------------------------------------------------------------------
    | Default download filename
    |--------------------------------------------------------------------------
    | Used by ICalendar::response() / the `ics` response macro.
    */
    'filename' => 'calendar.ics',

    /*
    |--------------------------------------------------------------------------
    | UID domain
    |--------------------------------------------------------------------------
    | The right-hand side of UIDs generated by the InteractsWithCalendar trait.
    | Defaults to the host of APP_URL when null.
    */
    'uid_domain' => null,

    /*
    |--------------------------------------------------------------------------
    | Optional persistence
    |--------------------------------------------------------------------------
    | Persistence and migration loading are separate, explicit choices. An
    | application using only ICS features never touches the database.
    */
    'persistence' => [
        'enabled' => false,
        'load_migrations' => false,
        'connection' => null,

        'tables' => [
            'calendar' => 'ical_calendars',
            'event' => 'ical_calendar_events',
            'participant' => 'ical_event_participants',
            'alarm' => 'ical_event_alarms',
        ],

        'models' => [
            'calendar' => Calendar::class,
            'event' => CalendarEvent::class,
            'participant' => EventParticipant::class,
            'alarm' => EventAlarm::class,
        ],

        'owner' => [
            'enabled' => false,
        ],

    ],

];
